### ISSUE TITLE
The checks for `_MSC_VER` and `__clang__` in `minconfig.hpp` should probably be reversed

### ISSUE THREAD

**Issue by pdimov** [MikePopoloski/boost_unordered#3]
https://github.com/MikePopoloski/boost_unordered/blob/8f14ca2aa0b2f0087d6c904e79ee65d88c70600b/include/boost/minconfig.hpp#L9

Clang-cl also defines `_MSC_VER`, and the "original" Boost.Config only defines `BOOST_MSVC` when the compiler is really MSVC, and not a pretender (such as clang-cl.)

**Comment by MikePopoloski** [comment]
Yeah, good catch.

**Comment by MikePopoloski** [comment]
Fixed in 0c35831302a5730052582de15b31a71c2c52f1e4
