### ISSUE TITLE
Boost 1.87?

### ISSUE THREAD

**Issue by ryobg** [MikePopoloski/boost_unordered#4]
Hello! Thank you for the great effort, I was really looking forward to find a standalone boost unordered :)

Would you mind to migrate to the latest 1.86 revision? It looks like even 1.87 beta is out too.

I have tried to do this myself, and hereby I share my experience:
* There are two dependencies in that `./make_unordered.sh` - bcp and coan
* `bcp` was easy to install with `sudo apt install  libboost1.83-tools-dev` 
* that `coan` was pita to build, the configure script was wrongly assuming big endian system, as well there was compilation error for a throw statement
* ran the `./make_unorederd.sh` and it broke I think?
* Apparently, it assumes thes repo to stay inside the home folder `cp ~/boost_unordered/include/boost/minconfig .` and this is inconvenient, why not just use the local filesystem?
* the `coan` thingie spews out several warnings
* I suppose I have built the output, but I don't know how to make it single header only

**Comment by MikePopoloski** [comment]
I was planning to just skip 1.86 and do an update for 1.87 once that's released. It seems like you got most of the way there yourself though.
* I don't remember coan being difficult to build locally but it's not something I've thought about in a while
* The script is basically whatever happened to work on my machine; feel free to put up a PR if you want generalize paths or whatever
* Once you have the output you can use the script in tools/acme.py along with the single_header_template.hpp file to produce the single header version.

For 1.87 I might produce a "two header" version -- one header with the unordered containers, and another with the concurrent containers. Haven't decided yet though.

**Comment by ryobg** [comment]
Thanks for the reply! I have thematically changed to a request for 1.87 then.

P.S. `./tools/acme.py ./single_header_template.hpp`

**Comment by MikePopoloski** [comment]
This is done
